export const TEMPLATE_EXPORT_INVOICE = {
  stt: "STT",
  khmshdon: "Ký hiệu mẫu số",
  khhdon: "Ký hiệu hóa đơn",
  shdon: "Số hoá đơn",
  tdlap: "Ngày lập",
  nbmst: "MST người bán",
  nbten: "Tên người bán",
  tgtcthue: "Tổng tiền trước thuế",
  tgtthue: "Tổng tiền thuế",
  ttcktmai: "Tổng tiền chiết khấu thương mại",
  tgtphi: "Tổng tiền Phí",
  tgtttbso: "Tổng tiền thanh toán",
  tthai: "Trạng thái hoá đơn",
}