export const TEMPLATE_EXPORT_PURCHASE_INVOICE = {
  stt: 'STT',
  khmshdon: 'Ký hiệu mẫu số',
  khhdon: 'Ký hiệu hóa đơn',
  shdon: 'Số hoá đơn',
  tdlap: 'Ngày lập',
  nbmst: 'MST người bán',
  nbten: 'Tên người bán',
  tgtcthue: 'Tổng tiền trước thuế',
  tgtthue: 'Tổng tiền thuế',
  ttcktmai: 'Tổng tiền chiết khấu thương mại',
  tgtphi: 'Tổng tiền Phí',
  tgtttbso: 'Tổng tiền thanh toán',
  tthai: 'Trạng thái hoá đơn',
  diengiai: 'Diễn giải',
  nmdchi: 'Địa chỉ người mua',
  nmten: 'Tên người mua',
  khmshdgoc: 'Ký hiệu mẫu số hóa đơn gốc',
  khhdgoc: 'Ký hiệu hóa đơn gốc',
  shdgoc: 'Số hóa đơn gốc',
};

export const TEMPLATE_EXPORT_SOLD_INVOICE = {
  stt: 'STT',
  khmshdon: 'Ký hiệu mẫu số',
  khhdon: 'Ký hiệu hóa đơn',
  shdon: 'Số hoá đơn',
  tdlap: 'Ngày lập',
  nmmst: 'MST người mua',
  nmten: 'Tên người mua',
  tgtcthue: 'Tổng tiền trước thuế',
  tgtthue: 'Tổng tiền thuế',
  ttcktmai: 'Tổng tiền chiết khấu thương mại',
  tgtttbso: 'Tổng tiền thanh toán',
  tthai: 'Trạng thái hoá đơn',
  diengiai: 'Diễn giải',
  khmshdgoc: 'Ký hiệu mẫu số hóa đơn gốc',
  khhdgoc: 'Ký hiệu hóa đơn gốc',
  shdgoc: 'Số hóa đơn gốc',
};

export const TEMPLATE_EXPORT_COMPARE_RESULT = {
  stt: 'STT',
  khmshdon: 'Ký hiệu mẫu số',
  khhdon: 'Ký hiệu hóa đơn',
  shdon: 'Số hoá đơn',
  tdlap: 'Ngày lập',
  nbmst: 'MST người bán',
  nbten: 'Tên người bán',
  nmmst: 'MST người mua',
  nmten: 'Tên người mua',
  tgtcthue: 'Tổng tiền trước thuế',
  tgtthue: 'Tổng tiền thuế',
  ttcktmai: 'Tổng tiền chiết khấu thương mại',
  tgtphi: 'Tổng tiền Phí',
  tgtttbso: 'Tổng tiền thanh toán',
  tthai: 'Trạng thái hoá đơn',
  diengiai: 'Diễn giải',
  nmdchi: 'Địa chỉ người mua',
  khmshdgoc: 'Ký hiệu mẫu số hóa đơn gốc',
  khhdgoc: 'Ký hiệu hóa đơn gốc',
  shdgoc: 'Số hóa đơn gốc',
};
